# --- START OF FILE contracts.py ---

from dataclasses import dataclass, field
from typing import Dict, Set, Optional


@dataclass
class RawAlphaSignal:
    """Represents a raw alpha signal generated by a factor module.
    The 'expected_value' is a required field, ensuring every signal
    is processed by the BayesianEVCalculator.

    Args:

    Returns:

    """
    symbol: str
    score: float
    confidence: float
    expected_value: float  
    components: Optional[Dict[str, float]] = None


@dataclass
class RiskBudget:
    """Defines the risk budget for a portfolio or a sleeve."""
    target_portfolio_exposure: float
    max_position_count: int


@dataclass
class StratifiedCandidatePool:
    """(Note: This class is less relevant in a pure sleeve-based model
    but is kept for potential future hybrid strategies.)

    Args:

    Returns:

    """
    conservative_candidates: Set[str]
    aggressive_candidates: Set[str]
    allocation_ratio: Dict[str, float]

    def get_all_candidates(self) -> Set[str]:
        """ """
        return self.conservative_candidates | self.aggressive_candidates

    @property
    def all_candidates(self) -> Set[str]:
        """ """
        return self.conservative_candidates.union(self.aggressive_candidates)

    @property
    def conservative_only(self) -> Set[str]:
        """ """
        return self.conservative_candidates - self.aggressive_candidates

    @property
    def aggressive_only(self) -> Set[str]:
        """ """
        return self.aggressive_candidates - self.conservative_candidates

    @property
    def consensus_candidates(self) -> Set[str]:
        """ """
        return self.conservative_candidates.intersection(self.aggressive_candidates)


# --- Type Aliases ---
RawAlphaSignalDict = Dict[str, RawAlphaSignal]
CandidatePool = Set[str]
FinalTargetPortfolio = Dict[str, float]
